---
abstract: 'Middleware for Profiling a Plack App'
author:
  - 'Takatoshi Kitano <kitano.tk {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Profiler-NYTProf
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Devel::NYTProf: 0
  Filter::Util::Call: 0
  Plack: 0
  Time::HiRes: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
